# Usar una imagen base de Node.js
FROM node:16

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo package.json y package-lock.json para instalar dependencias
COPY js_clase/package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar todos los archivos desde la carpeta js_clase
COPY js_clase /app/js_clase

# Copiar otros archivos HTML, CSS, e imágenes
COPY Proyecto_Ecomerce.html /app/
COPY Basica.css /app/
COPY Camisetas /app/Camisetas
COPY carrito /app/carrito
COPY Formulario /app/Formulario
COPY Diseño /app/Diseño
COPY logo /app/logo

# Exponer el puerto 3000
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]
